### ISSUE TITLE
ROS-melodic install removes CATKIN and destroys dependencies - melodic release?

### ISSUE THREAD

**Issue by habakuk39** [robotpilot/myahrs_driver#14]

**Comment by habakuk39** [comment]
@robotpilot : I am on Ubuntu 18.04

1.) I cannot install 
"sudo apt-get install **ros-indigo-myahrs-driver**"

2.) when I try to "**catkin_make**"  the "myahrs_driver.git" I get the missing "**roscpp**"- and missing "**roscppConfig.cmake**" - error message and cannot compile. So I installed "**ros-melodic-desktop-full**" für Ubuntu 18.04 as recommended, but this removes "catkin" from my ubuntu and kills dependencies such as "**python-catkin-pkg**", so that I cannot install Catkin anymore.

I cannot download and cannot compile your myahrs driver! What should I do?

Please help

**Comment by robotpilot** [comment]
Hi @habakuk39 ,
1) The myahrs_driver package now supports indigo and kinetic versions. You can install the package of the same ROS version you have installed.
https://index.ros.org/search/?term=myahrs_driver 

2) I did't release the melodic version, but you can use it after the source code build in the following way. There is no roscpp error. My computer is also Ubuntu 18.04 and I am using ROS melodic, but it builds without problems.
```
cd ~/catkin_ws/src
git clone https://github.com/robotpilot/myahrs_driver.git
cd ~/catkin_ws && catkin_make
```

**Comment by habakuk39** [comment]
Hi @robotpilot,

I am usung odroid C2 on Ubuntu 18.04 (3.16.65.39) from hardkernel.

When I install ros melodic exactly like described (http://wiki.ros.org/melodic/Installation/Ubuntu) I cannot 
"cd ~/catkin_ws && catkin_make"
because there is no catkin installed! (When it was workingly installed beforehand, it gets removed by the ros-meldoc installation.

When I try to (re)install catkin then by
"sudo apt install catkin"
I get the following error message:
Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information my help to resolve the situation:
The following packages have unmet dependencies:
catkin: Depends: python-catkin-pkg but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

What should I do?

Please help. Is there a possibility for your to up your compiled driver.pkg for melodic, so that I can avoid this catkin issue?

peter

**Comment by habakuk39** [comment]
no matter what I try - I cannot compile!

plz help

**Comment by robotpilot** [comment]
@habakuk39,

The problem you mentioned is not a problem with this package. Please post to the ROS community below.

http://answers.ros.org/questions/

**Comment by habakuk39** [comment]
@robotpilot:

I finally got it compiled. Let's say I learned a lot....

But now that the RViz is finally running, there is obviously no device connected.
There are several errors in the shell:

1.) MESA-LOADER: failed to retrieve device information

and:

2.) libGL error: unable to load driver: mali_drm_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver mali_drm

any suggestions

**Comment by robotpilot** [comment]
duplicated issue: https://github.com/robotpilot/myahrs_driver/issues/15
