### ISSUE TITLE
myahrs_driver - cannot load 'mali_drm_dri.so' and MESA LOADER fails to retrieve device information

### ISSUE THREAD

**Issue by habakuk39** [robotpilot/myahrs_driver#15]
@robotpilot:

I finally got it compiled. Let's say I learned a lot....
Thanks for sending me to the ros board.
People helped me out a lot.

But now that the RViz is finally running, there is obviously no device connected.
There are several errors in the shell:

1.) MESA-LOADER: failed to retrieve device information

and:

2.) libGL error: unable to load driver: mali_drm_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver mali_drm

any suggestions?

**Comment by robotpilot** [comment]
Hi @habakuk39 ,
This problem is not related to this package and ROS. This is a modified Ubuntu issue on the arm board you are using. Please contact SBC or modified Linux Image supplier.
