### ISSUE TITLE
Kinetic release and repo management

### ISSUE THREAD

**Issue by gstavrinos** [robotpilot/myahrs_driver#3]
Hello, 

We have been using your package in one of our robots for quite some time now. Since myAHRS+ is part of our robot's hardware, we have also included it in its stack. Our robot's stack is based on ROS Kinetic and since myahrs_driver has only been released for Indigo, we cannot release our package for everyone to use, because it is missing the myahrs_driver dependency. 

Could you please release the myahrs_driver package for Kinetic, to help the dependent packages have a release too?

I am willing to help with any way I can. If your time schedule is too tight, maybe you could give me permissions for the related repositories so I can make commits, accept pull requests etc, and make the release myself.

Thank you for your time,

George

**Comment by robotpilot** [comment]
@gstavrinos 

Thank you for your interest.
I will register the Kinetic Kame version of this package you mentioned until next week. :)

Thanks,

**Comment by robotpilot** [comment]
@gstavrinos 
FYI, https://github.com/ros/rosdistro/pull/15825

**Comment by gstavrinos** [comment]
Thank you very much for your quick response!!
